Integrate with the Mac Now Playing Info Center
CDrummond/cantata pull request #1699
Opened 2021-03-31 20:19 UTC by dphoyes

This adds MacOS support for controlling cantata via hardware media keys,
or via the OS's Now Playing widget. Implements #614 and #1347.

2021-03-31 20:40 UTC, Thaodan requested changes
See the attached comments.

2021-03-31 20:40 UTC, Thaodan commented on mac/macnowplaying.h
> + * Copyright (c) 2011-2021 Craig Drummond <craig.p.drummond@gmail.com>
The copyright is wrong it should be your name there.

2021-03-31 20:40 UTC, Thaodan commented on mac/macnowplaying.mm
> + *
Same again.

2021-03-31 20:40 UTC, Thaodan commented on mac/macnowplaying.mm
> +    connect(this, SIGNAL(setSeekId(qint32, quint32)), MPDConnection::self(), SLOT(setSeekId(qint32, quint32)));
I don't think Qt4 stlye connect should be used anymore.
See https://doc.qt.io/qt-5/signalsandslots.html

2021-03-31 20:40 UTC, Thaodan commented on CMakeLists.txt
> +    find_library(MAC_APPKIT_LIBRARY AppKit REQUIRED)
Should this not be optional to not break older releases?

2021-04-01 07:35 UTC, CDrummond commented on mac/macnowplaying.h
> + * Copyright (c) 2011-2021 Craig Drummond <craig.p.drummond@gmail.com>
I agree, this file is yours so feel free to add your name.

2021-04-01 07:37 UTC, CDrummond commented on CMakeLists.txt
> +    find_library(MAC_APPKIT_LIBRARY AppKit REQUIRED)
I don't see why - I'd imagine AppKit is standard on a Mac.

2021-04-01 07:37 UTC, CDrummond commented
Thanks for this. When you've updated the copyright I'll happily merge.

2021-04-01 12:01 UTC, dphoyes commented on mac/macnowplaying.h
> + * Copyright (c) 2011-2021 Craig Drummond <craig.p.drummond@gmail.com>
Thanks, updated.

2021-04-01 12:02 UTC, merged

2021-04-01 12:03 UTC, dphoyes commented on CMakeLists.txt
> +    find_library(MAC_APPKIT_LIBRARY AppKit REQUIRED)
https://developer.apple.com/documentation/appkit?language=objc says that AppKit is available in macOS 10.0+, which is the same as for Foundation.